### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Engine-VR#19]
Необходимо добавить описание проекта в README и в секции About

![image](https://user-images.githubusercontent.com/12235437/141067189-b1538440-4e96-4cbb-85da-99301816fabd.png)

**Comment by Eloren1** [comment]
About не могу редактировать

**Comment by Eloren1** [comment]
Файл для лендинга добавил

**Comment by CAPCHIK** [comment]
Сделал тебя админом, теперь можешь отредактировать

**Comment by Eloren1** [comment]
Осталось подтянуть на лендинг описание проекта, автообновление все еще не работает?

**Comment by CAPCHIK** [comment]
Автообновления и небыло, надо чтобы я руками подтвердил
А где файл? Не вижу его в мастере

**Comment by Eloren1** [comment]
Не в корне лежал файл, теперь все нормально
