### ISSUE TITLE
Отображение прогресса

### ISSUE THREAD

**Issue by darke333** [RTUITLab/Engine-VR#2]
Во время сборки необходимо отображать прогресс в виде UI. Сборка двигателя состоит из нескольких стадий, на каждой из которых может быть несколько элементов. Именно стадии и элементы на них и нужно показывать

**Comment by Eloren1** [comment]
Сделал отображение прогресса всей сборки и текущего этапа. Полоса слайдера продвигается по мере сборки. Канвас с прогрессом находится прямо в игровом мире, недалеко от самого двигателя.

![Progress_0](https://user-images.githubusercontent.com/46666053/115767132-7442b600-a3b1-11eb-8616-b19464e7965f.png)
![Progress_1](https://user-images.githubusercontent.com/46666053/115767152-7b69c400-a3b1-11eb-847f-abccbf4cc6ed.png)
