### ISSUE TITLE
Выбор или создание комнаты для подключения

### ISSUE THREAD

**Issue by darke333** [RTUITLab/Engine-VR#3]
Необходимо предоставить возможность выбора между существующими комнатами или создать свою. Выбор отобразить в UI.

**Comment by lysakovv** [comment]
Создал методы для создания своей комнаты и входа в случайную комнату. Также добавил возможность получения и отображения списка созданных комнат.
![image](https://user-images.githubusercontent.com/55603036/116123958-54223800-a6cc-11eb-97b6-0851634c5307.png)

**Comment by lysakovv** [comment]
Дополнительно исправил работу онлайна. Теперь игроки видят друг друга при заходе в одну комнату.
![image](https://user-images.githubusercontent.com/55603036/116124051-73b96080-a6cc-11eb-80f1-e090ee9dbae4.png)
