### ISSUE TITLE
Отображение ника

### ISSUE THREAD

**Issue by darke333** [RTUITLab/Engine-VR#4]
Над головой необходимо отображать ник пользователя. Необходимо дать возможность пользователю набрать ник самостоятельно или выбрать из случайно генерируемых.

Для клавиатуры советую данный ассет:
https://assetstore.unity.com/packages/tools/input-management/vrkeys-99222#content

**Comment by Eloren1** [comment]
Сделал возможность до запуска сборки ввести никнейм с клавиатуры или выбрать из предложенных (инженер, механик).

В объекте Canvas Nickname на компоненте NicknameChoose есть возможность выбрать сбрасывать ли никнейм после перезахода в главное меню или нет. Полезно на демонстрационных стендах, чтобы не сохранять чужие ники.

![Nickname_0](https://user-images.githubusercontent.com/46666053/115773435-f8e50280-a3b8-11eb-8c40-8eba89ad66ba.png)

**Comment by Eloren1** [comment]
Сделал синхронизацию никнеймов между игроками. Над каждым игроком правильно отображается его никнейм, который игрок ввел в главном меню. При входе в комнату игроки обмениваются никнеймами для синхронизации.

![image](https://user-images.githubusercontent.com/46666053/116130763-44a6ed00-a6d4-11eb-9967-cf744739bdd8.png)
![image](https://user-images.githubusercontent.com/46666053/116130794-4ec8eb80-a6d4-11eb-9d25-b6672804ec02.png)

**Comment by Eloren1** [comment]
Дополнительно добавил вращение никнейма к камере, чтобы он был читаемым с любой стороны

![YOt9t0rMF7o.jpg](https://user-images.githubusercontent.com/46666053/116393716-ab3e1f00-a82a-11eb-991a-bac8ca1f7a52.jpg)
![VRm03k-TnXI.jpg](https://user-images.githubusercontent.com/46666053/116393713-aa0cf200-a82a-11eb-9368-de8bc78887b3.jpg)
