### ISSUE TITLE
Отображение анимации в конце сборки

### ISSUE THREAD

**Issue by darke333** [RTUITLab/Engine-VR#5]
У двигателя есть конечная анимация, когда он полностью собран. В случае успешного выполнения сценария, необходимо эту анимацию показать.
Анимация находится в сцене Presentation

**Comment by Eloren1** [comment]
Сделал запуск анимации двигателя после окончания сборки. Вращается сам двигатель и его винт.

![image](https://user-images.githubusercontent.com/46666053/116400739-0c69f080-a833-11eb-9320-a90d928b1fdc.png)
![image](https://user-images.githubusercontent.com/46666053/116400831-29062880-a833-11eb-88de-bc5fc4c617e3.png)
