### ISSUE TITLE
Баг с установкой детали на место

### ISSUE THREAD

**Issue by darke333** [RTUITLab/Engine-VR#6]
Если деталь падает, при этом событие установки на место сработало, то объект спавнится на столе и ползет на свою позицию

**Comment by lysakovv** [comment]
В случае неудачной установки детали, она возвращается на точку появления - на стол.

https://user-images.githubusercontent.com/55603036/118144806-8a262280-b415-11eb-8b1e-364ce5e74db2.mp4
