### ISSUE TITLE
Просадка кадров при загрузке некоторых этапов

### ISSUE THREAD

**Issue by darke333** [RTUITLab/Engine-VR#8]
Во время загрузки некоторых этапов (например второго) симуляция подвисает. С помощью Profiler необходимо просмотреть, какой ресурс взывает просадки, и найти способ устранения лага.

**Comment by Eloren1** [comment]
Вся проблема была в `GameObject.Activate > Mesh.Bake Physx` — меш коллайдер генерировался в рантайме при включении. Теперь коллайдер генерируется заранее в «import time». Итого получается, что никаких просадок нет.
