### ISSUE TITLE
Анимация ходьбы

### ISSUE THREAD

**Issue by darke333** [RTUITLab/Engine-VR#9]
Анимация ходьбы сейчас работает на обратной кинематике. Необходимо найти и реализовать более надежный и красивый способ анимации напарника по сборке.

**Comment by lysakovv** [comment]
Реализовал передвижение с помощью трекпада на HTC VIVE Pro. Возможность телепорта отключена.

**Comment by D0rG** [comment]
@lysakovv я не вижу прикрепленный комит, но тут вопрос был в том, что движение ног на IK не хорошо работает, и стоит её заменить на обычную анимацию. Да и раньше и так движение работало по тачпаду.

**Comment by lysakovv** [comment]
Добавлены раздельные анимации ходьбы вперед, назад, влево, вправо. С помощью Blend Tree реализовано смешивание анимаций в зависимости от направления движения.

https://user-images.githubusercontent.com/55603036/118377283-fef38b00-b5d4-11eb-8062-a7ee105eb11f.mp4
